projects:
  hammystrading:
    schemaPath: src/graphql/schema.json
    includes:
      - /amplify/backend/api/hammystrading/schema.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: /amplify/backend/api/hammystrading
