projects:
  hammystrading:
    schemaPath: src/graphql/schema.json
    includes:
      - /amplify/backend/api/hammystrading/schema.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: /amplify/backend/api/hammystrading
  hammysweb:
    schemaPath: ../src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
